; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
board_build.filesystem = spiffs

lib_deps =
	https://github.com/me-no-dev/AsyncTCP
	https://github.com/me-no-dev/ESPAsyncWebServer
	ricmoo/QRCode @ ^0.0.1

build_flags =
	-DCORE_DEBUG_LEVEL=3
	-DUSE_SERIAL=true
	-DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
